import os
from datetime import datetime
from sqlalchemy.orm import Session
from app.models import Vulnerability, Target
from fastapi import HTTPException
from weasyprint import HTML

class AdvancedComplianceReporter:
    def __init__(self, db: Session):
        self.db = db

    def generate_html_report(self, target_id: int) -> str:
        target = self.db.query(Target).filter(Target.id == target_id).first()
        target_domain = target.domain if target else "Unknown Target"
        
        vulns = self.db.query(Vulnerability).filter(Vulnerability.target_id == target_id).all()
        
        total_vulns = len(vulns)
        severity_counts = {"Critical": 0, "High": 0, "Medium": 0, "Low": 0, "Info": 0}
        
        for v in vulns:
            sev = getattr(v, "severity", "Info")
            if sev in severity_counts:
                severity_counts[sev] += 1

        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title>AegisEngine Enterprise Security Report</title>
            <style>
                body {{ font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; margin: 0; padding: 30px; color: #2c3e50; background-color: #f8f9fa; }}
                .cover-page {{ page-break-after: always; text-align: center; padding-top: 150px; }}
                .cover-page h1 {{ font-size: 42px; color: #1a252f; margin-bottom: 10px; }}
                .cover-page h3 {{ font-size: 20px; color: #7f8c8d; font-weight: normal; }}
                .metadata {{ margin-top: 100px; font-size: 14px; color: #95a5a6; }}
                
                h2, h3 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 5px; }}
                .vuln-card {{ background: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.05); border-left: 5px solid #3498db; }}
                .vuln-card.Critical {{ border-left-color: #c0392b; }}
                .vuln-card.High {{ border-left-color: #e67e22; }}
                .vuln-card.Medium {{ border-left-color: #f1c40f; }}
                
                .badge {{ display: inline-block; padding: 4px 10px; font-size: 12px; font-weight: bold; border-radius: 4px; color: white; }}
                .badge.Critical {{ background-color: #c0392b; }}
                .badge.High {{ background-color: #e67e22; }}
                .badge.Medium {{ background-color: #f1c40f; color: #7f8c8d; }}
                .badge.Low {{ background-color: #3498db; }}
                .badge.Info {{ background-color: #2ecc71; }}
                
                pre {{ background: #2c3e50; color: #ecf0f1; padding: 12px; border-radius: 5px; font-size: 12px; overflow-x: auto; }}
                .section {{ margin-top: 40px; }}
            </style>
        </head>
        <body>
            <div class="cover-page">
                <h1>AegisEngine VAPT Report</h1>
                <h3>Enterprise Security & Compliance Assessment</h3>
                <p style="font-size: 22px; color: #2980b9; margin-top: 30px;">Target: <strong>{target_domain}</strong></p>
                <div class="metadata">
                    <p>Generated by AegisEngine Autonomous Security Scanner</p>
                    <p>Date: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC</p>
                </div>
            </div>

            <div class="section">
                <h2>1. Executive Summary</h2>
                <p>This report details the vulnerability assessment and penetration testing results conducted for <strong>{target_domain}</strong> using the AegisEngine platform. A total of <strong>{total_vulns}</strong> findings were identified.</p>
                
                <table style="width: 100%; margin-top: 20px; border-collapse: collapse;">
                    <tr style="background: #2c3e50; color: white;">
                        <th style="padding: 10px; text-align: left;">Severity</th>
                        <th style="padding: 10px; text-align: center;">Count</th>
                    </tr>
                    <tr><td style="padding: 8px; border: 1px solid #ddd;">Critical</td><td style="padding: 8px; border: 1px solid #ddd; text-align: center; color: #c0392b; font-weight: bold;">{severity_counts['Critical']}</td></tr>
                    <tr style="background: #fdfdfd;"><td style="padding: 8px; border: 1px solid #ddd;">High</td><td style="padding: 8px; border: 1px solid #ddd; text-align: center; color: #e67e22; font-weight: bold;">{severity_counts['High']}</td></tr>
                    <tr><td style="padding: 8px; border: 1px solid #ddd;">Medium</td><td style="padding: 8px; border: 1px solid #ddd; text-align: center; color: #f1c40f; font-weight: bold;">{severity_counts['Medium']}</td></tr>
                    <tr style="background: #fdfdfd;"><td style="padding: 8px; border: 1px solid #ddd;">Low</td><td style="padding: 8px; border: 1px solid #ddd; text-align: center; color: #3498db;">{severity_counts['Low']}</td></tr>
                    <tr><td style="padding: 8px; border: 1px solid #ddd;">Info</td><td style="padding: 8px; border: 1px solid #ddd; text-align: center; color: #2ecc71;">{severity_counts['Info']}</td></tr>
                </table>
            </div>

            <div class="section">
                <h2>2. Detailed Vulnerability Findings & Remediation</h2>
        """

        if not vulns:
            html_content += "<p>No vulnerabilities found or target not scanned yet.</p>"
        else:
            for idx, v in enumerate(vulns, 1):
                title = getattr(v, "title", "Unknown Vulnerability")
                sev = getattr(v, "severity", "Info")
                cwe = getattr(v, "cwe", "CWE-Unassigned")
                owasp = getattr(v, "owasp_category", "N/A")
                description = getattr(v, "description", "No description provided.")
                remediation = getattr(v, "remediation", "Apply standard security patches and input validation.")
                poc = getattr(v, "poc", "curl -X GET 'https://target.com/'")

                html_content += f"""
                <div class="vuln-card {sev}">
                    <h3>{idx}. {title}</h3>
                    <p><strong>Severity:</strong> <span class="badge {sev}">{sev}</span> &nbsp;&nbsp;|&nbsp;&nbsp; <strong>CWE:</strong> {cwe} &nbsp;&nbsp;|&nbsp;&nbsp; <strong>OWASP:</strong> {owasp}</p>
                    <p><strong>Description:</strong><br>{description}</p>
                    <p><strong>Proof of Concept (PoC / cURL):</strong></p>
                    <pre>{poc}</pre>
                    <p><strong>Remediation Advice:</strong><br>{remediation}</p>
                </div>
                """

        html_content += """
            </div>
        </body>
        </html>
        """
        return html_content

    def generate_pdf_report(self, target_id: int, output_pdf_path: str):
        html_content = self.generate_html_report(target_id)
        HTML(string=html_content).write_pdf(output_pdf_path)
        return output_pdf_path